configuration: Release
environment:
  packageVersion: 0.2.1

pull_requests:
  do_not_increment_build_number: true

init:
  - ps: $env:IsPrerelease = ($env:APPVEYOR_REPO_TAG -eq $False) -or ($env:APPVEYOR_REPO_BRANCH -ne "master")
  - ps: $env:buildVersion = if ($env:IsPrerelease -eq $False) {"$env:packageVersion"} else {"$env:packageVersion.$env:appveyor_build_number"}
  - ps: $env:nugetVersion = if ($env:APPVEYOR_REPO_BRANCH -eq "master") {"$env:buildVersion" }  else {"$env:packageVersion-$env:APPVEYOR_REPO_BRANCH$env:appveyor_build_number" }
  # send version back
  - ps: Update-AppveyorBuild -Version $env:buildVersion
  - ps: echo "PreRelease = $env:IsPrerelease"
  - ps: echo "BuildVersion = $env:buildVersion"
  - ps: echo "nugetVersion = $env:nugetVersion"

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

platform: Any CPU

before_build:
  - nuget restore

build:
  project: NewAudio.sln
  publish_nuget: false
  publish_nuget_symbols: false
  include_nuget_references: true


after_build:
  - ps: nuget pack VL.NewAudio.nuspec -version "$env:nugetVersion"

artifacts:
  - path: '*.nupkg'
    name: NewAudio
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: eo2oXlqnYoh9ksBlpuKuL1eDkqSC3SwQ3PXsG+eyk7hA6X6T+L3tFT+OfAoX+Eeq
    skip_symbols: true
    artifact: NewAudio
    on:
      appveyor_repo_tag: true
      